AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/console
    - active_any-slack.gemspec
    - Guardfile
    - vendor/bundle/**/*
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/LineLength:
  Max: 150

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb
